version: "3.9"

services:
  # Django service
  tejidoservice:
    build:
      context: .
      dockerfile: ./tejidos/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LETSENCRYPT_HOST=jorgeavm.top
      - LETSENCRYPT_EMAIL=javillarrm@eafit.edu.co
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - certbot
    restart: unless-stopped

  # Nginx reverse proxy service
  nginx-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tejidoservice
    restart: unless-stopped

  # Certbot service
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./nginx-conf:/etc/nginx/conf.d:ro
    command: ["certonly", "--webserver", "nginx", "-d", "jorgeavm.top", "--agree-tos", "-m", "javillarrm@eafit.edu.co"]

volumes:
  certbot-etc:
