version: "3.8"

services:
  # Django application service
  tejidos:
    image: jovillarrealm/dockerized-tejidos:latest
    build:
      context: . # Build the image from the current directory
    environment:
      - ALLOWED_HOSTS=jorgeavm.top
      # Add other Django environment variables here (optional)
    deploy:
      replicas: 3 # Scale to 3 replicas for redundancy

  # Reverse proxy service with HTTPS
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443" # Map container port 443 to host port 443 (HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount custom Nginx config
      - certbot-etc:/etc/letsencrypt # Optional: Mount volume for persistent certs
      - certbot-var:/var/lib/letsencrypt # Optional: Mount volume for persistent certs
    depends_on:
      - tejidos
    deploy:
      replicas: 1 # One Nginx container needed

volumes:
  certbot-etc:
    # Replace with the actual host path where certificates are stored (if different)
    hostPath: /etc/letsencrypt
  certbot-var:
    # Replace with the actual host path where certificates are stored (if different)
    hostPath: /var/lib/letsencrypt

