# Generated by Django 5.0.2 on 2024-02-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatronModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('detalles', models.TextField()),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('profundidad', models.FloatField()),
            ],
        ),
    ]
