# Generated by Django 5.0.3 on 2024-03-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatronModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('detalles', models.TextField()),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('profundidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('descuento', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30, unique=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='amigurumi.patronmodel')),
            ],
        ),
    ]
