# Generated by Django 5.0.2 on 2024-02-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronmodel',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
