# Generated by Django 5.0.3 on 2024-03-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronmodel',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='patronmodel',
            name='profundidad',
        ),
        migrations.AddField(
            model_name='patronmodel',
            name='tamaño',
            field=models.CharField(choices=[('GR', 'Grande'), ('MD', 'Mediano'), ('PQ', 'Pequeño')], default='GR', max_length=2),
        ),
    ]
