# Generated by Django 5.0.3 on 2024-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0002_remove_patronmodel_ancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronmodel',
            name='imagen',
            field=models.ImageField(default='Messi', upload_to='static/patrones'),
        ),
        migrations.AlterField(
            model_name='patronmodel',
            name='tamaño',
            field=models.CharField(choices=[('GR', 'Grande'), ('MD', 'Mediano'), ('PQ', 'Pequeño')], max_length=2),
        ),
    ]
