# Generated by Django 5.0.2 on 2024-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0002_patronmodel_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
