# Generated by Django 5.0.3 on 2024-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0003_patronmodel_imagen_alter_patronmodel_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronmodel',
            name='imagen',
            field=models.ImageField(upload_to='static/patrones'),
        ),
    ]
