# Generated by Django 5.0.3 on 2024-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0003_alter_patronmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronmodel',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
