# Generated by Django 5.0.3 on 2024-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0004_patronmodel_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronmodel',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
