# Generated by Django 5.0.3 on 2024-03-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0004_alter_patronmodel_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronmodel',
            name='imagen',
        ),
    ]
