# Generated by Django 5.0.3 on 2024-03-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigurumi', '0005_remove_patronmodel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='patrones'),
        ),
    ]
