name: Docker Image CI

on:
  push:
    branches: [ main, feat/jorge ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jovillarrealm/dockerized-tejidos:latest
      
    - name: Docker Push
      run: docker push jovillarrealm/dockerized-tejidos:latest

